 <b>Pandas is a data analysis tool, you can get acquainted with your data by cleaning, transforming and analyzing it: <b>
    
    
1. NLP with Pandas
2. What's the mean, median, max, min of each column?
3. data distribution of a column

<b>Step 1: Install library<b>

condas install pandas

or 

pip install pandas

In [2]:
import pandas as pd

# NLP with Pandas

#### Dataset

10,000 records extracted from twitter for trending topic of - #AvengersEndgame 

https://www.kaggle.com/datasets/kavita5/twitter-dataset-avengersendgame?resource=download

In [3]:
Avengers_tweets = pd.read_csv('tweets.csv', encoding = "ISO-8859-1")
Avengers_tweets

,Unnamed: 0,text,favorited,favoriteCount,replyToSN,created,truncated,replyToSID,id,replyToUID,statusSource,screenName,retweetCount,isRetweet,retweeted,longitude,latitude
0,1,RT @mrvelstan: literally nobody:\r\nme:\r\n\r\...,False,0,NaN,2019-04-23 10:43:30,False,NaN,1120639328034676737,NaN,"<a href=""http://twitter.com/download/android"" ...",DavidAc96,637,True,False,NaN,NaN
1,2,"RT @agntecarter: im emotional, sorry!!\r\n\r\...",False,0,NaN,2019-04-23 10:43:30,False,NaN,1120639325199196160,NaN,"<a href=""http://twitter.com/download/iphone"" r...",NRmalaa,302,True,False,NaN,NaN
2,3,saving these bingo cards for tomorrow \r\n©\r\...,False,0,NaN,2019-04-23 10:43:30,False,NaN,1120639324683292674,NaN,"<a href=""http://twitter.com/download/iphone"" r...",jijitsuu,0,False,False,NaN,NaN
3,4,RT @HelloBoon: Man these #AvengersEndgame ads ...,False,0,NaN,2019-04-23 10:43:29,False,NaN,1120639323328540672,NaN,"<a href=""http://twitter.com/download/iphone"" r...",SahapunB,23781,True,False,NaN,NaN
4,5,"RT @Marvel: We salute you, @ChrisEvans! #Capta...",False,0,NaN,2019-04-23 10:43:29,False,NaN,1120639321571074048,NaN,"<a href=""http://twitter.com/download/iphone"" r...",stella22_97,13067,True,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,14996,RT @natsdany: First time Last...,False,0,NaN,2019-04-23 09:22:03,False,NaN,1120618828918951937,NaN,"<a href=""http://twitter.com/download/android"" ...",tommysboi,33,True,False,NaN,NaN
14996,14997,RT @MTVNEWS: The #AvengersEndgame cast has see...,False,0,NaN,2019-04-23 09:22:03,False,NaN,1120618828038311936,NaN,"<a href=""http://twitter.com/download/iphone"" r...",kimberleywithae,2307,True,False,NaN,NaN
14997,14998,@SPICinemas kindly announce the approximate ti...,False,0,SPICinemas,2019-04-23 09:22:02,False,NaN,1120618823667920896,919079586.0,"<a href=""http://twitter.com/download/android"" ...",Gnanavel07,0,False,False,NaN,NaN
14998,14999,"RT @Marvel: We salute you, @ChrisEvans! #Capta...",False,0,NaN,2019-04-23 09:22:02,False,NaN,1120618823600803840,NaN,"<a href=""https://mobile.twitter.com"" rel=""nofo...",_moonljght,13167,True,False,NaN,NaN
14999,15000,"RT @Avengers: Welcome to the party, @RobertDow...",False,0,NaN,2019-04-23 09:22:01,False,NaN,1120618822300569601,NaN,"<a href=""http://twitter.com/download/android"" ...",CaterinaCabrel1,10736,True,False,NaN,NaN

# Lambda function

A lambda function is a small function containing a single expression.

It can be anonymous, you don't need to assign a name to it

We can also use lambda functions when we have to pass a small function to another function

## Using Lambda function in Pandas

In [5]:
Avengers_tweets['adjusted_retweet']=Avengers_tweets.apply(lambda x: x['retweetCount']+3,axis=1)
Avengers_tweets

,Unnamed: 0,text,favorited,favoriteCount,replyToSN,created,truncated,replyToSID,id,replyToUID,statusSource,screenName,retweetCount,isRetweet,retweeted,longitude,latitude,adjusted_retweet
0,1,RT @mrvelstan: literally nobody:\r\nme:\r\n\r\...,False,0,NaN,2019-04-23 10:43:30,False,NaN,1120639328034676737,NaN,"<a href=""http://twitter.com/download/android"" ...",DavidAc96,637,True,False,NaN,NaN,640
1,2,"RT @agntecarter: im emotional, sorry!!\r\n\r\...",False,0,NaN,2019-04-23 10:43:30,False,NaN,1120639325199196160,NaN,"<a href=""http://twitter.com/download/iphone"" r...",NRmalaa,302,True,False,NaN,NaN,305
2,3,saving these bingo cards for tomorrow \r\n©\r\...,False,0,NaN,2019-04-23 10:43:30,False,NaN,1120639324683292674,NaN,"<a href=""http://twitter.com/download/iphone"" r...",jijitsuu,0,False,False,NaN,NaN,3
3,4,RT @HelloBoon: Man these #AvengersEndgame ads ...,False,0,NaN,2019-04-23 10:43:29,False,NaN,1120639323328540672,NaN,"<a href=""http://twitter.com/download/iphone"" r...",SahapunB,23781,True,False,NaN,NaN,23784
4,5,"RT @Marvel: We salute you, @ChrisEvans! #Capta...",False,0,NaN,2019-04-23 10:43:29,False,NaN,1120639321571074048,NaN,"<a href=""http://twitter.com/download/iphone"" r...",stella22_97,13067,True,False,NaN,NaN,13070
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,14996,RT @natsdany: First time Last...,False,0,NaN,2019-04-23 09:22:03,False,NaN,1120618828918951937,NaN,"<a href=""http://twitter.com/download/android"" ...",tommysboi,33,True,False,NaN,NaN,36
14996,14997,RT @MTVNEWS: The #AvengersEndgame cast has see...,False,0,NaN,2019-04-23 09:22:03,False,NaN,1120618828038311936,NaN,"<a href=""http://twitter.com/download/iphone"" r...",kimberleywithae,2307,True,False,NaN,NaN,2310
14997,14998,@SPICinemas kindly announce the approximate ti...,False,0,SPICinemas,2019-04-23 09:22:02,False,NaN,1120618823667920896,919079586.0,"<a href=""http://twitter.com/download/android"" ...",Gnanavel07,0,False,False,NaN,NaN,3
14998,14999,"RT @Marvel: We salute you, @ChrisEvans! #Capta...",False,0,NaN,2019-04-23 09:22:02,False,NaN,1120618823600803840,NaN,"<a href=""https://mobile.twitter.com"" rel=""nofo...",_moonljght,13167,True,False,NaN,NaN,13170
14999,15000,"RT @Avengers: Welcome to the party, @RobertDow...",False,0,NaN,2019-04-23 09:22:01,False,NaN,1120618822300569601,NaN,"<a href=""http://twitter.com/download/android"" ...",CaterinaCabrel1,10736,True,False,NaN,NaN,10739

## Task 1: Preprocess data in dataframe

In [5]:
import nltk
from nltk.stem.porter import PorterStemmer
import emoji
import re
import string

In [7]:
porter_stemmer = PorterStemmer()
stopwords = nltk.corpus.stopwords.words('english')

def preprocessing_text(text):
    #remove punctuation

    return no_stopwords

,Unnamed: 0,text,favorited,favoriteCount,replyToSN,created,truncated,replyToSID,id,replyToUID,statusSource,screenName,retweetCount,isRetweet,retweeted,longitude,latitude,adjusted_retweet,preprocess_text
0,1,RT @mrvelstan: literally nobody:\r\nme:\r\n\r\...,False,0,NaN,2019-04-23 10:43:30,False,NaN,1120639328034676737,NaN,"<a href=""http://twitter.com/download/android"" ...",DavidAc96,637,True,False,NaN,NaN,640,rt mrvelstan literally nobody\r\nme\r\n\r\nave...
1,2,"RT @agntecarter: im emotional, sorry!!\r\n\r\...",False,0,NaN,2019-04-23 10:43:30,False,NaN,1120639325199196160,NaN,"<a href=""http://twitter.com/download/iphone"" r...",NRmalaa,302,True,False,NaN,NaN,305,rt agntecarter im emotional sorry\r\n\r\n2014...
2,3,saving these bingo cards for tomorrow \r\n©\r\...,False,0,NaN,2019-04-23 10:43:30,False,NaN,1120639324683292674,NaN,"<a href=""http://twitter.com/download/iphone"" r...",jijitsuu,0,False,False,NaN,NaN,3,saving bingo cards tomorrow \r\ncopyright\r\n ...
3,4,RT @HelloBoon: Man these #AvengersEndgame ads ...,False,0,NaN,2019-04-23 10:43:29,False,NaN,1120639323328540672,NaN,"<a href=""http://twitter.com/download/iphone"" r...",SahapunB,23781,True,False,NaN,NaN,23784,rt helloboon man avengersendgame ads everywhere
4,5,"RT @Marvel: We salute you, @ChrisEvans! #Capta...",False,0,NaN,2019-04-23 10:43:29,False,NaN,1120639321571074048,NaN,"<a href=""http://twitter.com/download/iphone"" r...",stella22_97,13067,True,False,NaN,NaN,13070,rt marvel salute chrisevans captainamerica ave...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,14996,RT @natsdany: First time Last...,False,0,NaN,2019-04-23 09:22:03,False,NaN,1120618828918951937,NaN,"<a href=""http://twitter.com/download/android"" ...",tommysboi,33,True,False,NaN,NaN,36,rt natsdany first time last t...
14996,14997,RT @MTVNEWS: The #AvengersEndgame cast has see...,False,0,NaN,2019-04-23 09:22:03,False,NaN,1120618828038311936,NaN,"<a href=""http://twitter.com/download/iphone"" r...",kimberleywithae,2307,True,False,NaN,NaN,2310,rt mtvnews avengersendgame cast seen lot years...
14997,14998,@SPICinemas kindly announce the approximate ti...,False,0,SPICinemas,2019-04-23 09:22:02,False,NaN,1120618823667920896,919079586.0,"<a href=""http://twitter.com/download/android"" ...",Gnanavel07,0,False,False,NaN,NaN,3,spicinemas kindly announce approximate timings...
14998,14999,"RT @Marvel: We salute you, @ChrisEvans! #Capta...",False,0,NaN,2019-04-23 09:22:02,False,NaN,1120618823600803840,NaN,"<a href=""https://mobile.twitter.com"" rel=""nofo...",_moonljght,13167,True,False,NaN,NaN,13170,rt marvel salute chrisevans captainamerica ave...
14999,15000,"RT @Avengers: Welcome to the party, @RobertDow...",False,0,NaN,2019-04-23 09:22:01,False,NaN,1120618822300569601,NaN,"<a href=""http://twitter.com/download/android"" ...",CaterinaCabrel1,10736,True,False,NaN,NaN,10739,rt avengers welcome party robertdowneyjr ironm...

## Task 2: Further cleaning your text 

Now observe your data and think about how to further preprocess your text

In [26]:
# each column in pandas is a series, a series is similar to a list, you can access the data entry like this
Avengers_tweets['preprocess_text'][2]

'saving bingo cards tomorrow \r\ncopyright\r\n avengersendgame '

In [31]:
def further_preprocess(text):

    return line

## Task 3: Generate wordcloud for tweets

In [33]:
from wordcloud import WordCloud, STOPWORDS

In [34]:
wordcloud2 = WordCloud(width= 3000, height = 2000, random_state=1, background_color='salmon', colormap='Pastel1', collocations=False, stopwords = STOPWORDS).generate(' '.join(Avengers_tweets['further_preprocess']))

In [35]:
import matplotlib.pyplot as plt

## Summary statistics

In [44]:
peiguins = pd.read_csv('penguins.csv')
peiguins

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,4,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,5,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...,...
339,340,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,341,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,342,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,343,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,344,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [46]:
peiguins[["bill_length_mm", "bill_depth_mm"]].median()

bill_length_mm    44.45
bill_depth_mm     17.30
dtype: float64

In [47]:
peiguins[["bill_length_mm", "bill_depth_mm"]].describe()

       bill_length_mm  bill_depth_mm
count      342.000000     342.000000
mean        43.921930      17.151170
std          5.459584       1.974793
min         32.100000      13.100000
25%         39.225000      15.600000
50%         44.450000      17.300000
75%         48.500000      18.700000
max         59.600000      21.500000

In [ ]:
# aggregate by group

In [51]:
peiguins[["bill_length_mm", "island"]].groupby("island").mean()

           bill_length_mm
island
Biscoe          45.257485
Dream           44.167742
Torgersen       38.950980

In [52]:
# count the number in each group
peiguins[["bill_length_mm", "island"]].groupby("island")["island"].count()

island
Biscoe       168
Dream        124
Torgersen     52
Name: island, dtype: int64

## Task 4: Explore the penguin dataset